"""add.

Revision ID: fc13e5c6ad67
Revises: 884099d6503f
Create Date: 2026-02-17 12:21:24.474314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc13e5c6ad67'
down_revision: Union[str, Sequence[str], None] = '884099d6503f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'addresses', ['address_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###
